apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
-  https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.4/manifests/install.yaml

configMapGenerator:
  - name: argocd-cmp-plugins
    files:
      - plugin.yaml

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      group: apps
      version: v1
      kind: Service
      name: argocd-server
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: argocd-server
      spec:
        type: LoadBalancer
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
    path: sidecar-patch.yaml

